# Generated by Django 2.2.5 on 2021-06-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default='False')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=800)),
            ],
        ),
    ]
